Changed in the workflow

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -2,8 +2,9 @@
 # about the building blocks of GitHub Actions
 
 name: 01 - Building Blocks
-
-on: workflow_dispatch
+on: 
+  workflow_dispatch:
+  push:
 
 jobs:
   echo-hello:
@@ -14,9 +15,13 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: Successful step
+      #    - name: Successful step
+      #  run: |
+      #    echo "I will succeed"
+      #    exit 0
+      - name: Failed step
         run: |
-          echo "I will succeed"
-          exit 0
+          echo "I will fail"
+          exit 1
       - name: Say goodbye
         run: echo "Goodbye!"
